### ISSUE TITLE
When the proxy is opened too much, it will no longer connect

### ISSUE THREAD

**Issue by tahitimoon** [AirdropFamilyIDN-V2-0/grass#2]
Thank you very much for sharing the software. I encounter connection issues whenever I open multiple proxies, and the earnings always show as 0. Have you experienced this situation? It works fine when I turn off all the proxies.
<img width="745" alt="image" src="https://github.com/user-attachments/assets/07bee88f-e1da-4116-8b82-212d258dccf9">

**Comment by Brajamustii** [comment]
20 proxy setting
